### PR TITLE
[KOA-4829]: Add new typography tokens

### PR DESCRIPTION
**Pull request by anambl**
Remember to include the following changes:

- [x] `UNRELEASED.md` (See [How to write a good changelog entry](https://github.com/Skyscanner/backpack-foundations/blob/main/CHANGELOG_FORMAT.md))
- [ ] `README.md`
- [ ] Tests
- [ ] Docs (either update [backpack-docs](https://github.com/Skyscanner/backpack-docs) now, or create a follow up ticket)

### CODE REVIEW

**Review by olliecurtis — APPROVED** [review]
LGTM!

One question are we not adding the new bigger sizes 5xl - 8xl in this PR like app already have done? Or have I missed something?

https://github.com/Skyscanner/backpack-foundations/blob/main/packages/bpk-foundations-common/app/typography.json#L27

**Comment by anambl** [comment]
> LGTM!
> 
> One question are we not adding the new bigger sizes 5xl - 8xl in this PR like app already have done? Or have I missed something?
> 
> https://github.com/Skyscanner/backpack-foundations/blob/main/packages/bpk-foundations-common/app/typography.json#L27

I remember we discussed a while ago that there are no use cases for those sizes and while we do support them, there's no need to add them right now. Let me double check with Adam, as it might be good to just add them now to make sure there's no confusion in the future if someone wants to use them!

**Comment by olliecurtis** [comment]
> I remember we discussed a while ago that there are no use cases for those sizes and while we do support them, there's no need to add them right now. Let me double check with Adam, as it might be good to just add them now to make sure there's no confusion in the future if someone wants to use them!

Sure thing! I guess if we want to go down that path we need to sync with @frugoman and @marianeum with this as if we don't add them maybe we should remove them from the apps typography also just to avoid confusion and keep the platforms aligned

**Comment by anambl** [comment]
> > I remember we discussed a while ago that there are no use cases for those sizes and while we do support them, there's no need to add them right now. Let me double check with Adam, as it might be good to just add them now to make sure there's no confusion in the future if someone wants to use them!
> 
> Sure thing! I guess if we want to go down that path we need to sync with @frugoman and @marianeum with this as if we don't add them maybe we should remove them from the apps typography also just to avoid confusion and keep the platforms aligned

Think it's better to just add them! Otherwise we risk engineers thinking the style in their design doesn't exist and even use tokens instead. Will add them now!

**Review by olliecurtis — APPROVED** [review]

**Pull request merged**
